"""Property-based tests for clone script.

Feature: openclaw-telegram-bot
Tests Property 20 from the design document.
"""

import io
import tarfile
import tempfile
from pathlib import Path
from typing import Dict, List

import pytest
from hypothesis import given, settings, strategies as st, HealthCheck, assume

from scripts.clone import (
    CloneExporter,
    content_contains_secrets,
    file_contains_secrets,
    should_exclude_path,
    validate_no_secrets,
    EXCLUDED_DIRS,
    EXCLUDED_FILENAMES,
    SECRET_PATTERNS,
)


# --- Strategies ---

# Characters safe for file content (printable ASCII, no NUL bytes)
safe_chars = st.characters(whitelist_categories=("L", "N", "P", "S", "Z"))

# Generate realistic Groq API keys: gsk_ followed by 20-50 ASCII alphanumeric chars
# The regex in clone.py is gsk_[A-Za-z0-9]{20,}, so we must use only ASCII alphanumeric
_ascii_alnum = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789"
groq_key_strategy = st.builds(
    lambda suffix: f"gsk_{suffix}",
    st.text(
        min_size=20,
        max_size=50,
        alphabet=st.sampled_from(_ascii_alnum),
    ),
)

# Generate realistic Telegram bot tokens: 10 digits : 35 alphanumeric/dash/underscore chars
telegram_token_strategy = st.builds(
    lambda digits, suffix: f"{digits}:{suffix}",
    st.from_regex(r"[0-9]{10}", fullmatch=True),
    st.text(
        min_size=35,
        max_size=35,
        alphabet=st.sampled_from(
            "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789_-"
        ),
    ),
)

# Generate content that is guaranteed clean (no secret patterns)
clean_content_strategy = st.text(
    min_size=0,
    max_size=200,
    alphabet=st.sampled_from("abcdefghijklmnopqrstuvwxyz \n=:{}[]#"),
)

# Generate file names that are safe (not .env)
safe_filename_strategy = st.sampled_from(
    [
        "config.yaml",
        "main.py",
        "utils.py",
        "README.md",
        "test_foo.py",
        "helpers.py",
        "settings.yaml",
        "providers.yaml",
    ]
)

# Generate directory components that are safe (not in EXCLUDED_DIRS)
safe_dir_strategy = st.sampled_from(["src", "config", "tests", "scripts", "assets", "lib"])

# Generate excluded directory names
excluded_dir_strategy = st.sampled_from(sorted(EXCLUDED_DIRS))


class TestCloneExportExcludesSecrets:
    """Property 20: Clone Export Excludes Secrets

    For any clone export archive generated by the clone script, the archive
    SHALL NOT contain .env files or any files containing API keys or tokens.

    **Validates: Requirements 13.1**
    """

    # --- content_contains_secrets tests ---

    @given(key=groq_key_strategy)
    @settings(max_examples=100, deadline=None)
    def test_groq_keys_always_detected(self, key: str):
        """Property 20: Any Groq API key pattern (gsk_...) is detected as a secret.

        **Validates: Requirements 13.1**
        """
        assert content_contains_secrets(key), (
            f"Groq key should be detected as secret: {key[:15]}..."
        )

    @given(token=telegram_token_strategy)
    @settings(max_examples=100, deadline=None)
    def test_telegram_tokens_always_detected(self, token: str):
        """Property 20: Any Telegram bot token pattern is detected as a secret.

        **Validates: Requirements 13.1**
        """
        assert content_contains_secrets(token), (
            f"Telegram token should be detected as secret: {token[:15]}..."
        )

    @given(
        prefix=clean_content_strategy,
        secret=st.one_of(groq_key_strategy, telegram_token_strategy),
        suffix=clean_content_strategy,
    )
    @settings(max_examples=100, deadline=None)
    def test_secrets_detected_in_surrounding_content(
        self, prefix: str, secret: str, suffix: str
    ):
        """Property 20: Secrets embedded in larger content are still detected.

        **Validates: Requirements 13.1**
        """
        content = f"{prefix}\n{secret}\n{suffix}"
        assert content_contains_secrets(content), (
            "Secret embedded in content should still be detected"
        )

    @given(content=clean_content_strategy)
    @settings(max_examples=100, deadline=None)
    def test_clean_content_not_flagged(self, content: str):
        """Property 20: Content without secret patterns is not flagged.

        **Validates: Requirements 13.1**
        """
        # Ensure the generated content doesn't accidentally match secret patterns
        for pattern in SECRET_PATTERNS:
            assume(not pattern.search(content))

        assert not content_contains_secrets(content), (
            f"Clean content should not be flagged: {content!r}"
        )

    # --- should_exclude_path tests ---

    @given(
        excluded_dir=excluded_dir_strategy,
        filename=safe_filename_strategy,
    )
    @settings(max_examples=100, deadline=None)
    def test_excluded_dirs_always_excluded(self, excluded_dir: str, filename: str):
        """Property 20: Paths under excluded directories are always excluded.

        **Validates: Requirements 13.1**
        """
        path = Path(excluded_dir) / filename
        assert should_exclude_path(path), (
            f"Path in excluded dir should be excluded: {path}"
        )

    @given(data=st.data())
    @settings(max_examples=100, deadline=None)
    def test_env_files_always_excluded(self, data):
        """Property 20: .env files are always excluded regardless of directory.

        **Validates: Requirements 13.1**
        """
        parent = data.draw(safe_dir_strategy)
        path = Path(parent) / ".env"
        assert should_exclude_path(path), (
            f".env file should always be excluded: {path}"
        )

    @given(
        parent=safe_dir_strategy,
        filename=safe_filename_strategy,
    )
    @settings(max_examples=100, deadline=None)
    def test_safe_paths_not_excluded(self, parent: str, filename: str):
        """Property 20: Safe paths in non-excluded dirs are not excluded.

        **Validates: Requirements 13.1**
        """
        path = Path(parent) / filename
        assert not should_exclude_path(path), (
            f"Safe path should not be excluded: {path}"
        )

    # --- file_contains_secrets tests ---

    @given(secret=st.one_of(groq_key_strategy, telegram_token_strategy))
    @settings(max_examples=50, deadline=None)
    def test_file_with_secrets_detected(self, secret: str):
        """Property 20: Files containing secret patterns are detected.

        **Validates: Requirements 13.1**
        """
        with tempfile.TemporaryDirectory() as tmpdir:
            filepath = Path(tmpdir) / "test_file.txt"
            filepath.write_text(f"some config\nkey={secret}\nmore config")
            assert file_contains_secrets(filepath), (
                "File with secret should be detected"
            )

    @given(content=clean_content_strategy)
    @settings(max_examples=50, deadline=None)
    def test_file_without_secrets_passes(self, content: str):
        """Property 20: Files without secret patterns pass the check.

        **Validates: Requirements 13.1**
        """
        for pattern in SECRET_PATTERNS:
            assume(not pattern.search(content))

        with tempfile.TemporaryDirectory() as tmpdir:
            filepath = Path(tmpdir) / "clean_file.txt"
            filepath.write_text(content)
            assert not file_contains_secrets(filepath), (
                "Clean file should not be flagged"
            )

    # --- validate_no_secrets on archives ---

    @given(secret=st.one_of(groq_key_strategy, telegram_token_strategy))
    @settings(max_examples=30, deadline=None, suppress_health_check=[HealthCheck.too_slow])
    def test_archive_with_secret_content_flagged(self, secret: str):
        """Property 20: Archives containing files with secrets are flagged by validation.

        **Validates: Requirements 13.1**
        """
        with tempfile.TemporaryDirectory() as tmpdir:
            archive_path = Path(tmpdir) / "test.tar.gz"

            with tarfile.open(str(archive_path), "w:gz") as tar:
                # Add a file with secret content
                content = f"API_KEY={secret}".encode("utf-8")
                info = tarfile.TarInfo(name="openclaw/config/leaked.yaml")
                info.size = len(content)
                tar.addfile(info, io.BytesIO(content))

            violations = validate_no_secrets(archive_path)
            assert len(violations) > 0, (
                "Archive with secret content should have violations"
            )

    @given(data=st.data())
    @settings(max_examples=30, deadline=None, suppress_health_check=[HealthCheck.too_slow])
    def test_archive_with_env_file_flagged(self, data):
        """Property 20: Archives containing .env files are flagged by validation.

        **Validates: Requirements 13.1**
        """
        parent_dir = data.draw(st.sampled_from(["openclaw", "openclaw/config", "openclaw/src"]))

        with tempfile.TemporaryDirectory() as tmpdir:
            archive_path = Path(tmpdir) / "test.tar.gz"

            with tarfile.open(str(archive_path), "w:gz") as tar:
                content = b"TELEGRAM_BOT_TOKEN=safe_placeholder"
                info = tarfile.TarInfo(name=f"{parent_dir}/.env")
                info.size = len(content)
                tar.addfile(info, io.BytesIO(content))

            violations = validate_no_secrets(archive_path)
            assert len(violations) > 0, (
                "Archive with .env file should have violations"
            )
            assert any("excluded filename" in v for v in violations), (
                "Violation should mention excluded filename"
            )

    @given(
        filenames=st.lists(safe_filename_strategy, min_size=1, max_size=5),
        contents=st.lists(clean_content_strategy, min_size=1, max_size=5),
    )
    @settings(max_examples=30, deadline=None, suppress_health_check=[HealthCheck.too_slow])
    def test_clean_archive_passes_validation(self, filenames: List[str], contents: List[str]):
        """Property 20: Archives with only clean files pass validation.

        **Validates: Requirements 13.1**
        """
        # Ensure no accidental secret matches
        for content in contents:
            for pattern in SECRET_PATTERNS:
                assume(not pattern.search(content))

        with tempfile.TemporaryDirectory() as tmpdir:
            archive_path = Path(tmpdir) / "test.tar.gz"

            with tarfile.open(str(archive_path), "w:gz") as tar:
                for i, (fname, content) in enumerate(
                    zip(filenames, contents)
                ):
                    data = content.encode("utf-8")
                    info = tarfile.TarInfo(name=f"openclaw/src/{fname}_{i}")
                    info.size = len(data)
                    tar.addfile(info, io.BytesIO(data))

            violations = validate_no_secrets(archive_path)
            assert len(violations) == 0, (
                f"Clean archive should have no violations, got: {violations}"
            )

    # --- Full CloneExporter.export() integration ---

    @given(
        secret=st.one_of(groq_key_strategy, telegram_token_strategy),
        clean_content=clean_content_strategy,
    )
    @settings(max_examples=20, deadline=None, suppress_health_check=[HealthCheck.too_slow])
    def test_exporter_never_includes_secrets_in_archive(
        self, secret: str, clean_content: str
    ):
        """Property 20: CloneExporter.export() never produces an archive containing secrets.

        Creates a project with both clean files and files containing secrets,
        then verifies the exported archive contains zero secret violations.

        **Validates: Requirements 13.1**
        """
        for pattern in SECRET_PATTERNS:
            assume(not pattern.search(clean_content))

        with tempfile.TemporaryDirectory() as tmpdir:
            project_dir = Path(tmpdir) / "project"
            project_dir.mkdir()

            # Create config directory with clean config
            config_dir = project_dir / "config"
            config_dir.mkdir()
            (config_dir / "config.yaml").write_text(
                f"bot:\n  default_provider: groq\n  note: {clean_content}\n"
            )
            (config_dir / "permissions.yaml").write_text("admins: []\nusers: []\n")
            (config_dir / "providers.yaml").write_text("groq:\n  enabled: true\n")

            # Create a .env file with a real secret — must be excluded
            (config_dir / ".env").write_text(f"GROQ_API_KEY={secret}\n")

            # Create src directory with clean and secret-containing files
            src_dir = project_dir / "src"
            src_dir.mkdir()
            (src_dir / "main.py").write_text(f"# Main module\nprint('hello')\n")
            (src_dir / "leaked.py").write_text(
                f"# Oops, hardcoded secret\nAPI_KEY = '{secret}'\n"
            )

            # Create project files
            (project_dir / "pyproject.toml").write_text("[project]\nname = 'openclaw'\n")

            # Export
            output_path = Path(tmpdir) / "clone.tar.gz"
            exporter = CloneExporter(project_dir=str(project_dir))
            result = exporter.export(output_path=str(output_path))

            # Validate: the archive must have zero secret violations
            violations = validate_no_secrets(result)
            assert len(violations) == 0, (
                f"Export archive must not contain secrets, got violations: {violations}"
            )

    @given(data=st.data())
    @settings(max_examples=20, deadline=None, suppress_health_check=[HealthCheck.too_slow])
    def test_exporter_never_includes_env_files(self, data):
        """Property 20: CloneExporter.export() never includes .env files in the archive.

        **Validates: Requirements 13.1**
        """
        with tempfile.TemporaryDirectory() as tmpdir:
            project_dir = Path(tmpdir) / "project"
            project_dir.mkdir()

            # Create config directory
            config_dir = project_dir / "config"
            config_dir.mkdir()
            (config_dir / "config.yaml").write_text("bot:\n  default_provider: groq\n")
            (config_dir / "permissions.yaml").write_text("admins: []\n")
            (config_dir / "providers.yaml").write_text("groq:\n  enabled: true\n")

            # Create .env in multiple locations
            (config_dir / ".env").write_text("TOKEN=placeholder\n")
            (project_dir / ".env").write_text("TOKEN=placeholder\n")

            src_dir = project_dir / "src"
            src_dir.mkdir()
            (src_dir / ".env").write_text("TOKEN=placeholder\n")
            (src_dir / "app.py").write_text("print('app')\n")

            # Export
            output_path = Path(tmpdir) / "clone.tar.gz"
            exporter = CloneExporter(project_dir=str(project_dir))
            result = exporter.export(output_path=str(output_path))

            # Check: no .env files in the archive
            with tarfile.open(str(result), "r:gz") as tar:
                for member in tar.getmembers():
                    assert Path(member.name).name != ".env", (
                        f"Archive must not contain .env files, found: {member.name}"
                    )

    @given(
        secret=st.one_of(groq_key_strategy, telegram_token_strategy),
    )
    @settings(max_examples=20, deadline=None, suppress_health_check=[HealthCheck.too_slow])
    def test_exporter_includes_env_template_without_real_secrets(self, secret: str):
        """Property 20: The generated .env.template in the archive contains no real secrets.

        **Validates: Requirements 13.1**
        """
        with tempfile.TemporaryDirectory() as tmpdir:
            project_dir = Path(tmpdir) / "project"
            project_dir.mkdir()

            config_dir = project_dir / "config"
            config_dir.mkdir()
            (config_dir / "config.yaml").write_text("bot:\n  default_provider: groq\n")
            (config_dir / "permissions.yaml").write_text("admins: []\n")
            (config_dir / "providers.yaml").write_text("groq:\n  enabled: true\n")

            # Real .env with secret
            (config_dir / ".env").write_text(f"GROQ_API_KEY={secret}\n")

            # Export
            output_path = Path(tmpdir) / "clone.tar.gz"
            exporter = CloneExporter(project_dir=str(project_dir))
            result = exporter.export(output_path=str(output_path))

            # Find and check .env.template in archive
            with tarfile.open(str(result), "r:gz") as tar:
                template_found = False
                for member in tar.getmembers():
                    if member.name.endswith(".env.template"):
                        template_found = True
                        f = tar.extractfile(member)
                        assert f is not None
                        template_content = f.read().decode("utf-8")
                        f.close()

                        # Template must not contain the real secret
                        assert secret not in template_content, (
                            "Template must not contain real secrets"
                        )
                        assert not content_contains_secrets(template_content), (
                            "Template content must pass secret detection"
                        )

                assert template_found, "Archive should contain .env.template"
